global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "spring-backend"
    metrics_path: "/api/actuator/prometheus"
    static_configs:
      - targets: ["spring-backend:8080"]

  - job_name: "python-agent"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["python-agent:8000"]
